"""init subscription tables with cascade delete

Revision ID: 067cc4ef0945
Revises: 
Create Date: 2025-11-13 20:25:22.896009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '067cc4ef0945'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('identifiers', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aliases', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supported_actions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscribe_count', sa.Integer(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'entity_type', 'identifiers', 'user_id', name='uq_subscription_entity_user')
    )
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_display_name'), 'subscriptions', ['display_name'], unique=False)
    op.create_index(op.f('ix_subscriptions_platform'), 'subscriptions', ['platform'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('subscription_embeddings',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('embedding_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_embedded_at', sa.DateTime(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_embeddings')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_platform'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_display_name'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
